name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행됨

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: 의존성 패키지 설치
        run: npm install

      - name: 프로젝트 빌드
        run: npm run build
        env:
          CI: false  # 빌드 경고를 에러로 처리하지 않도록 설정

      - name: AWS 자격증명 구성
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 배포
        run: |
          aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

